### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Cideg** [comment]
The coin is not degradable via Randomx. A pool cannot be created. very suspicious as no announcement !!!

**Comment by goodthebest** [comment]
Hey, I'm trying to compile from your git source I'm not able to compile both on ubuntu 16.04 and ubuntu 18.04.

If I follow monero guidelines for compilation, when I apply those to your source code I end getting compiled Monero binaries.

Please let me know how to compile Tesoro binaries. Also having issue with your pool repo.

**Comment by goodthebest** [comment]
I do not see any branch with v0.1.0.0, all I can see is, branches from Monero repo into yours. No matter what branch I git checkout it eventually compiles Monero binaries, no way to figure out where is Tesoro real source code.

**Comment by Cideg** [comment]
@goodthebest
https://github.com/Tesoro-Dev/tesoro.git

```
[1] On Debian/Ubuntu libgtest-dev only includes sources and headers. You must build the library binary manually. This can be done with the following command sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/ [2] libnorm-dev is needed if your zmq library was built with libnorm, and not needed otherwise

Install all dependencies at once on Debian/Ubuntu:

sudo apt update && sudo apt install build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev qttools5-dev-tools libhidapi-dev libusb-dev libprotobuf-dev protobuf-compiler

Install all dependencies at once on macOS with the provided Brewfile: brew update && brew bundle --file=contrib/brew/Brewfile

FreeBSD one liner for required to build dependencies pkg install git gmake cmake pkgconf boost-libs libzmq libsodium```

2.
git submodule init && git submodule update

3. make

**Pull request merged**
